# RedisBungee configuration file.
# PLEASE READ THE WIKI: https://github.com/Limework/RedisBungee/wiki

# The Redis server you use.
# Get Redis from http://redis.io/
redis-server: 127.0.0.1
redis-port: 6379

# OPTIONAL: If your Redis server or sentinel(s) uses AUTH, set the password required.
# WARNING: Leaving your Redis server or sentinel exposed without a password is extremely unsafe
# and could cause issues like data not being sync and etc.
redis-password: ""

# since redis can support ssl by version 6 you can use ssl in redis bungee too!
# its' recommended to use redis with ssl to encrypt the traffic.
useSSL: false

#################################################################
# REDIS SENTINEL
# WARNING: THIS BETA AND NOT TESTED REPORT ANY ISSUES at issues pages in
# https://github.com/limework/redisbungee

# If enabled config options redis-server, redis-port and redis-password will be ignored.
use-sentinel: false

# you can have many sentinels as you want as long its like this format
#  sentinels:
#    - "<ip-address>:<port>"
#    - .....
#
sentinels:
  - "127.0.0.1:26379"
  - "127.0.0.1:26378"
  - "127.0.0.1:26377"

# enables ssl for sentinels connections.
use-SSL-sentinels: false
# to enable ssl for master and salve just set useSSL: true

# Sentinel password
sentinel-password: ""

# Your master name
master-name: mymaster
master-password: ""
##################################################################

# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10


# An identifier for this BungeeCord instance. Will randomly generate a UUID String if leaving it blank.
server-id: "test1"

# Should use random string? if this  is enabled the proxy id will be like this if server-id is test1: "test1-66cd2aeb-91f3-43a7-a106-e0307b098652"
# or if id is limework-bungee it will be "limework-bungee-66cd2aeb-91f3-43a7-a106-e0307b098652"
# this great for servers who run replicas in Kubernetes or any auto deploying replica service
# and used for if proxy died in a kubernetes network and deleted then new proxy setup itself.
use-random-id-string: false

# Whether or not RedisBungee should install its version of regular BungeeCord commands.
# Often, the RedisBungee commands are desired, but in some cases someone may wish to
# override the commands using another plugin.
#
# If you are just denying access to the commands, RedisBungee uses the default BungeeCord
# permissions - just deny them and access will be denied.
#
# Please note that with build 787+, most commands overridden by RedisBungee were moved to
# modules, and these must be disabled or overridden yourself.
register-bungee-commands: true

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
exempt-ip-addresses: []